# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-paginate-multiple

# --- General options --- #
# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://michelesanges.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Bit Error Rate

# Short description of your site
description: A virtual proof that name is awesome!

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Blog: "blog"
  Cicloturismo: "cicloturismo"
  Social:
    - Facebook: "https://www.facebook.com/sanges.michele"
    - Anobii: "http://www.anobii.com/michelesanges/books"
#    - Instagram: "https://www.instagram.com/michele.sanges/"
    #- GitHub: "https://github.com/michelesanges/"
  Photography:
    - Photovogue: "http://www.vogue.it/photovogue/portfolio/?id=149678"
    #- Stream: "https://photos.app.goo.gl/U4ibwYJIhElqmwH73"
    - Les parisiens: "https://goo.gl/photos/qZsTiEjBd1VjQbcv7"
    #- Hotel rooms: "https://photos.app.goo.gl/D4oRKW04Ajh1LNzP2"
    #- Sport Courts: "https://photos.app.goo.gl/kLQcjkq3taKOlvDq1"
  #Photography: "photography"
  Prova: "photography"
  About: "about"
  #Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
#avatar: "/img/author.jpg"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Michele Sanges
  email: "michele.sanges@gmail.com"
  facebook: sanges.michele  # eg. daattali
  #instagram: https://www.instagram.com/michele.sanges/
  google-photo: https://goo.gl/photos/J6n4SpRfPnE5ZsZh6
  anobii: http://www.anobii.com/michelesanges/books
  #google-maps: /bike_tracks/
  github: michelesanges    # eg. daattali
  twitter: yourname   # eg. daattali
  linkedin: yourlink  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: yourlink  # eg. "3943160/daattali"

  # social icons and sharing options
social:
  - icon:	facebook
    image:       "/img/facebook.png"
    target:      "_blank"
    url:	https://www.facebook.com/sanges.michele
    desc: Connect with me on Facebook
    share_url: https://www.facebook.com/sanges.michele
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	instagram
    image:       "/img/instagram.png"
    target:      "_blank"
    url:	https://www.instagram.com/michele.sanges/
    desc: Follow me on Instagram
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="


  - icon:	google-foto
    image:       "/img/google_foto.png"
    target:      "_blank"
    url:	https://goo.gl/photos/J6n4SpRfPnE5ZsZh6
    desc: See my Google Photo Stream
    share_url: 
    share_title: ?t=
    share_link: "&amp;u="

  - icon:       anobii
    image:       "/img/anobii.png"
    target:      "_blank"
    url:        http://www.anobii.com/michelesanges/books
    desc: Follow me on Anobii
    share_url:
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    image:       "/img/github.png"
    target:      "_blank"
    url:	https://github.com/michelesanges/
    desc:	Fork me on Github
    share_url:
    share_title:
    share_link:
 

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: true
  instagram: true
  google-photo: true
  anobii: true
  #google-maps: true
  email: false
  twitter: false
  github: false
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: "michelesanges"

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
#timezone: "America/Vancouver"
#markdown: kramdown
#highlighter: rouge
#permalink: /:year-:month-:day-:title/

#paginate: 5
#paginate_path: "/blog/page:num"

paginate_multiple:
  - paginate: 5
    paginate_path: '/blog/page:num'
    sub_dir: '/blog'
  - paginate: 5
    paginate_path: '/blog/general/page:num/'
    sub_dir: '/general'
  - paginate: 5
    paginate_path: '/blog/photography/page:num/'
    sub_dir: '/photography'
    
# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
